### ISSUE TITLE
gettin an error when making predictions

### ISSUE THREAD

**Issue by lucanico** [GauravPandeyLab/MetaClean#1]
Dear developers,

I am testing MetaClean package on my dataset, and  I am having an error at the last step of the workflow , when I use the built model to make predictions on an extended data set.

When running the following 
`EIC_predictions <- getPredicitons(model = metaclean_modelRP, testData = pqm_testmatrix, eicColumn = "EICNo")`

R returns this error: 

```
Error in data.frame(..., check.names = FALSE) : 
  arguments imply differing number of rows: 3666, 2899

```
3666  corresponds to the number  of groups in my xsFilled object and , therefore, the number of rows in my test matrix "pqm_testmatrix" in the function above.

I am wondering where I am going wrong. Also, I have observed I have a number  of `NA`  in  the `TPASR_mean` parameter within the "pqm_testmatrix"  and I was wondering if that could affect the outcome of the classification.

Thanks for your attention

**Comment by KelseyChetnik** [comment]
Hi lucanico,

From what you describe, it's most likely the `NA` values causing the issue. Could you try filtering out any rows containing NA values in your data frame and see if you are able to run `getPredictions()`?
